### ISSUE TITLE
Dividir as referências de header em objetos independentes

### ISSUE THREAD

**Issue by bryanlincoln** [PEQUI-VSSS/VSSS-EMC#45]
Criar os CPPs para os HPPs que são apenas referênciados e não são tratados como objetos independentes para que o make consiga fazer uma compilação mais eficiente.
Ao criar os CPPs, adicionar as regras de compilação no Makefile.

**Comment by danielfaleiro** [comment]
- [ ] camcap.hpp
- [ ] strategy.hpp
- [ ] strategyGUI.hpp
- [ ] Ann.hpp
- [ ] controlGUI.hpp
- [ ] Kalman_Filter.hpp
- [ ] SerialW.hpp
- [ ] ImageView.hpp
- [ ] stringtodouble.hpp

**Comment by danielfaleiro** [comment]
filechooser.o adicionado em #60

**Comment by danielfaleiro** [comment]
controlGUI, serialW e ImageView adicionados em #68
