### ISSUE TITLE
Valores de posição da interface assumem valores com muitas casas decimais e buga a interface.

### ISSUE THREAD

**Issue by danielfaleiro** [PEQUI-VSSS/VSSS-EMC#79]
É necessário limitar as casas decimais da posição dos robôs na interface ou arrendondar, já que a posição sempre assume um valor inteiro.

**Comment by lucasilvassis** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [RESOLVER](https://trello.com/c/nTrVDRkn/21-resolver)

**Comment by walissong** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [RESOLVER](https://trello.com/c/nTrVDRkn/21-resolver)

**Comment by danielfaleiro** [comment]
Resolvido em #87
